language: node_js
node_js:
- 6.10.1
branches:
  only:
  - development
  - test-site-development
  except:
  - master
  - conteudo
git:
  depth: 1
before_install:
- npm install -g hexo-cli
- npm install -g grunt-cli
- npm install -g bower
- npm install
- cd themes/tranquilpeak/
- npm install
- bower install
- grunt buildProd
- cd ../../
install:
- hexo generate
before_script:
- git config --global user.name 'Josenivaldo Benito Jr'
- git config --global user.email 'jrbenito@benito.qsl.br'
- sed -i'' "s~git@github.com:jrbenito/benito.com.br.git~https://${GH_TOKEN}:x-oauth-basic@github.com/jrbenito/benito.com.br.git~" _config.yml
- git clone https://github.com/jrbenito/benito.com.br.git .deploy_git -b conteudo
script:
- grunt s3-prod-deploy
- hexo deploy --silent
after_success:
- grunt sns
env:
  global:
  - secure: O5f2zGaXraEVUOIkoo1FpaXfrjoRpeJAz7YbDhqeWvhg/TP3KDZdE3Te3pFh9i6VaSJqPTWQIqxcCRQn0kQpz592xLmMxENmCyD8hMhJW5NN4bCgbemUzCx6Enk4fPCc7+r8iclzgAF/XbbwKRZ/u/sgBDnBW7epSixFrRXIZ+Nuvq2RqzPxUEkvfsvn/RpA6WjA+xdVXk/je1Fjr2GxlI6YENq35gVPFLub1vD/mxTCW6TqLwVfZbaGCICm6aOUxZWiiGJ6nEqThDoyQXu8+TsyBMAP+VdJdBoPLLzydhBvmOda7ctzSXX4eMU6CIFp0WuIQr3xKi3ZljylafF6NIGb1LBkLVrbC/jO0lK9kNGjvJIGllyPl1hqrLttNmCeYKM9uktZ8C0VFhcxo0bT2LkM5QAcizMomz1bDJ92S9Cr2R+vKD9kGk17ScJLBGJb2jpUfWWDMrN4q+YVg/JOgeQUCuC4x6tmbhHF++Dx7LbR7Sd12a7X4Kf2juAdjEnO828Mz49EG0uHfKR1CcOumRBzNcEEUs17Kuy6pTQK+eFXEh2gDWpbcuoz+F89x1RoJ2BIeusfAOHuXBsFlChIvDPmIRPW2l9pglnTSFWqgjcfhLWIvIDMeNleq5clWuNjloHk/eg+Fz2qPq6LmSIdOhoEH/xRGyb8DZ34hJLKW/Q=
  - secure: bsmjzMqApTjofgAcAKDWNRSUMlglhV8EHR8FD+wGStLFx6sfdkAYTodCvLB2gajtJb/R4S9gL7UabTX57WfLyTj9y8EdR9l2EbmuF5/lpWeQxvFM8yocxL0kznHpX+OnDLzJ/Afea8W+fFoMGN+82TfkrKPY8ppO+KjSpMCEK9HK77etmdr9jyAtndjYjMZFMzcHWaTscadu4feq1eqdoKy2OV6q9gqyAtgOw1itDoqXzh82HPC4MGpGQtvFBTeFIIqviHWYytSAVlVkh0/g3ZgTU6jQJ4EeWgayDauSs4/tsaDAvKM9Imw6+upH3VDptidp/D16IchrHJ5dzm9y3yuUyI22kI1f8HRfcMxmuFqUOzwzpl9HMB7noPR95HM9yu2udX6N1D8lp6JHriKfdfG2WyTdaqO2a0EMBwNxP0FQH/BeRtKy0uVI3I93jI+JCycUGYOnXbByCUCBC4V8XdA2KFH0nDiPHSDEoc+RsUiRK3zptzTk9Bf2l2bdZP3fNov7k6DInS8D1YjWOATkgVp1DgEOtQYXHI5T0cpk/oDgFhXDmwBoNQyTpDgfRpFqNfWodUsV72jIuVM1ahrI7sPuz3S+v6WwF8KQL/iH4lupDB4OlCCcqZDWeQzLGS/zXB6WfyHAoLBEz2KdVLChNqbXCtVY0W75H1br0IZn/gs=
  - secure: A84t9ASnL11WFrqLjV9K7/Q+9fbkfOxqz7MiLauK9iYoyredcKqj5Jp7yh8ybt2VbibYDUB/Mo7vmGmi7LsiAdTbzkmGcjyfHcd2AQh52sWlTZOCX3GedqVsWeyq44TdDAFtfUCwIerKHCEGMyLKRC/NWjcpRzrT4hfgQ6yeACtYLIletzrOWKOcfbSGL5YaZ6yY5V3kDWzzTqWElAR7ROCDIzDH4CtIydRflDUNSK3y8Xvbu/i2LAjPrxUv9LeSFz0vvzbu/WO23jZZFti3vRqZG/iAqcWZTBY3j+87g6+DvevzhmotnwIodZgd7MO+/YSdvL8PzBwVfiVISWdq53nG5PPOyQzxY6sS76dt+09KLEYp1FpinjMbEqNWjvCohszj0VdfdfDYLMTYTDcj5RVOM+wcaCU53zLp9qQdYuF+Mhg0QFn3kJurkbp3l6QJDaX9WBZH9r7dBZLqDna8JV+9PPI/e+5+CHXRlsDF8VLR8d63/oOFmHlmd/lHv5Uo+596eqSfwp16RvHpiO96nqQgD+SYhoPoGbWfn7E4fwXUCiD+TNPo5WZwWyjC3qzQowlcZ6nAGRLQu+Q8V/MfpRc2Kf3kFpKjISBodUv6YivUSVhM1Dr2NJK7u+NFa+N/R3XCiAuEkYtMrPX85P8mmH0MqeghkXusKu4cX+gktgQ=
  - secure: bY0O92GKQbUJoC6n4imype2YWYCUAp886uPQBMc9ZPuzliQFhjHC7FvAXHJB8VZYcl8DkpF5cwLdC1UogOTXeuGMEL+sVAnSQiEjoh3FO4moju6azrg+QeuToal9spuY7fWgDM9Pk23J0f1fNPn4n9YNVA82BZeQ9iFJzd8kRwAAv7X4phY7AJjY7PbsE1PjbL81FpS3yxkFdCeUI9xJPJpR91Wt1Em4yC26Ko3563RPfc2+5fQDFY4O9NGQN6nVHXFb9Il3dv/4J6Ek9C534EuQpmYonDxj+kqVi5UW0W/4ITQR8OuTw4knw2m/LdqrnawnJe2l/1WwuBugcItvfmwUdfr96wN8TdWYcXWQ6x4ujGtJvIkTruvWV83DrwEM7Iej3bq3XHn+BV7J9oOElrnCOo04T3isAQ7h/gMqz1xIw2iob1LNnt4YVcq0jlhIHmQJnlL8cQxjjPWaXBd6c+1Lwis8wmY6v4Y5lvFIhQCcdplsd6eOBKEvHyAQ4tbMuB+oRJWUSS5qTwZcbZpK6YuyBfynd/SJGA3X3LFN2jO3STfnH9YNN4C0EQZ3l4U8Vjqq0nBRQrIFG7U/UjCVi91T6uF9dZii7s43I2yGbCXcrPJ/KNeVRp0w0IjLy8U0IE4RPnjV254woqrNmXUNG4Pb/F6ZA320YYJyiveXw7w=
  - secure: XsaslKJoywExyrnr12GQCsevqrtTM+fghbAxnzid5sOo41yrt4xYCGHnktMGqe8ygvQGWqxMqSF4IZ2G8gn6X5TrkaNL+6xSDOqrzOln6F236HFKD+ubfORKiIrR6ZAqS3i3HrREkcLmvgVqHCeQW9QnFizccHFwx943uUIWl7D9i6oJcAwPbFasGaQ5F7O9BESNx7xnaHUdhYFC3nwmv/CngaxdpBjOpw5LTMU72qVgeJSVI5swR1C0EjhukPuD7FHE3qLcScrdFjftP2dBXCLmwcK9IGv0pbxoE+wLjvYnkGD6IWp1ynna3H3pto2eUogR0BEVc8dxc7vydrExxwNw7Djl9ap/7DNajaO8mWpYo1b1lZZg68rmkH36Gzf+c+7CyO55e0ddVNEMdW1S67ffY/k0OKLLHe4+jyC3x6IKiJK1URnC3lvHh7rdfOgQvwcMXzXMILG1T4pxHqlu+etoH3M9p3V3xuyFENHwQ4XSOFIcI3ogmrX/9zlUDdEhDt3K5dNj+peVFB96ZLoGRbOFtB5etXTJlgod1ls0eUxiMJb87dCOUfFCOWMhPNdGBbqyXCGwNahMao2EbLYHw/oF+222PG2D1ZeGZIKbeG6VsygHgkVYxF7StT93qtyr1BF3i8JCEuhalA/Dbjxxcjzcj5N1hfM0ZrbTJytI8eU=
